#!/bin/sh

# welcome to the 21th century
alias cat='bat'
alias diff='delta'
alias df='duf'
alias du='dust'
alias ls='exa'
alias vi='nvim'
alias vim='nvim'
alias watch='viddy'

# dangerous
# alias find='fd'
# alias cut='choose'
# alias grep='rg'
# alias ps='procs'

# safety first
alias mkdir='mkdir -pv'
alias mv='mv -iv'
alias rm='rm -v'
alias cp='cp -iv'

# goes to clipboard selection
alias yank='yank -- xsel -b'

# ls options
alias ls='ls -h --color=always --group-directories-first'
alias la='ls -al'              # all files and dirs
alias lh='ls -a | egrep "^\."' # only hidden
alias ll='ls -l'               # long format
alias lt='ls -aT | bat'        # tree listing

alias l='ls'

# correct typos
alias py='python'
alias pytohn='python'
alias vu='nvim'
alias vo='nvim'

# poetry stuff
alias ppy='poetry run python'
alias pty='poetry run ptpython'
alias flask='poetry run python -m flask'

# git stuff
alias g='git'
alias gbr='git branch'
alias gcm='git commit -a -m'
alias gco='git checkout'
alias gdf='git diff'
alias gdt='git difftool'
alias gll='git log --oneline --no-merges'
alias gpl='git pull'
alias gps='git push'
alias gst='git status'

# vim stuff
alias vsp='nvim -O'
alias vdf='nvim -d'
alias vtb='nvim -p'
alias fastvim='nvim -n -u NONE -i NONE -N'

# misc
alias anki="~/Downloads/anki-2.1.35-linux-amd64/bin/anki"
alias stow_dot="stow -v --no-folding --dotfiles -t ~ -d ~/.dotfiles ."

alias encf="openssl enc -e -aes256 -in"
alias decf="openssl enc -d -aes256 -in"
