#!/bin/sh

spell() {
	if [[ "$#" -eq 0 ]]; then
		cat /usr/share/dict/words |
			fzf --preview 'dict -d wn {} | fold -w $COLUMNS -s' --height=80% --preview-window=up:60% --layout=default |
			xargs dict -d wn | yank
	else
		cat /usr/share/dict/words |
			fzf --query $1 --preview 'dict -d wn {} | fold -w $COLUMNS -s' --height=80% --preview-window=up:60% --layout=default |
			xargs dict -d wn | yank
	fi
}

rgi() {
	if [ ! "$#" -gt 0 ]; then
		echo "Need a string to search for!"
		return 1
	fi
	rg --files-with-matches --no-messages "$1" | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}"
}

fcd() {
    local searchdir

    if [ -n "$1" ]; then
        searchdir="$1"
    else
        searchdir="$HOME"
    fi

    # Create a temporary file
    local tmpfile
    tmpfile=$(mktemp)

    # Use find and fzf to select a directory
    find "$searchdir" \( ! -regex '.*/\..*' \) ! -name __pycache__ -type d | fzf > "$tmpfile"
    local destdir
    destdir=$(cat "$tmpfile")
    rm -f "$tmpfile"

    # If no directory is selected, return with an error
    if [ -z "$destdir" ]; then
        return 1
    fi

    # Change to the selected directory
    cd "$destdir"
}

fkill() {
	local pid
	if [ "$UID" != "0" ]; then
		pid=$(ps -f -u $UID | sed 1d | fzf -m --preview='' | awk '{print $2}')
	else
		pid=$(ps -ef | sed 1d | fzf -m --preview='' | awk '{print $2}')
	fi

	if [ "x$pid" != "x" ]; then
		echo $pid | xargs kill -${1:-9}
	fi
}

fzf-man-widget() {
	batman="man {1} | col -bx | bat --language=man --plain --color always --theme=\"Monokai Extended\""
	man -k . | sort |
		awk -v cyan=$(tput setaf 6) -v blue=$(tput setaf 4) -v res=$(tput sgr0) -v bld=$(tput bold) '{ $1=cyan bld $1; $2=res blue;} 1' |
		fzf \
			-q "$1" \
			--ansi \
			--tiebreak=begin \
			--prompt=' Man > ' \
			--preview-window '50%,rounded,<50(up,85%,border-bottom)' \
			--preview "${batman}" \
			--bind "enter:execute(man {1})" \
			--bind "alt-c:+change-preview(cht.sh {1})+change-prompt(ﯽ Cheat > )" \
			--bind "alt-m:+change-preview(${batman})+change-prompt( Man > )" \
			--bind "alt-t:+change-preview(tldr --color=always {1})+change-prompt(ﳁ TLDR > )"
	zle reset-prompt
}
# bindkey '^m' fzf-man-widget
# zle -N fzf-man-widget

n ()
{
    # Block nesting of nnn in subshells
    [ "${NNNLVL:-0}" -eq 0 ] || {
        echo "nnn is already running"
        return
    }

    # The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
    # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
    # see. To cd on quit only on ^G, remove the "export" and make sure not to
    # use a custom path, i.e. set NNN_TMPFILE *exactly* as follows:
    #      NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    # The command builtin allows one to alias nnn to n, if desired, without
    # making an infinitely recursive alias
    command nnn "$@"

    [ ! -f "$NNN_TMPFILE" ] || {
        . "$NNN_TMPFILE"
        rm -f "$NNN_TMPFILE" > /dev/null
    }
}

topmem() {
    ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem | head
}
