#! /bin/sh

# start daemons
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x clipmenud > /dev/null || clipmenud &
pgrep -x picom > /dev/null || picom --experimental-backends &
pgrep -x polybar > /dev/null || polybar &
pgrep -x redshift > /dev/null || redshift &
pgrep -x unclutter > /dev/null || unclutter &

setxkbmap -model thinkpad -layout br -variant abnt
feh --randomize --bg-fill ~/MEGA/wallpapers/

# set wm config

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# App rules

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
