preload = /home/neumann/.wallpapers/thomas_cole-the_course_of_empire_1-_the_savage_state-1834-obelisk-art-history.jpg
preload = /home/neumann/.wallpapers/thomas_cole-the_course_of_empire_2-_the_pastoral_state-1834-obelisk-art-history.jpg
preload = /home/neumann/.wallpapers/thomas_cole-the_course_of_empire_3-_the_consummation_of_empire-1836-obelisk-art-history-1.jpg
preload = /home/neumann/.wallpapers/thomas_cole-the_course_of_empire_4-_destruction-1836-obelisk-art-history.jpg
preload = /home/neumann/.wallpapers/thomas_cole-the_course_of_empire_5-_desolation-1836-obelisk-art-history.jpg

wallpaper = {
    monitor = DP-2
    path = /home/neumann/.wallpapers/thomas_cole-the_course_of_empire_1-_the_savage_state-1834-obelisk-art-history.jpg
}

wallpaper = {
    monitor = eDP-1
    path = /home/neumann/.wallpapers/thomas_cole-the_course_of_empire_1-_the_savage_state-1834-obelisk-art-history.jpg
}

splash = false
ipc = true
