#!/usr/bin/env sh

# WM config
if xrandr --query | grep 'HDMI2 connected'; then
	echo "ksdnakjdsssa"
	xrandr --output eDP1 --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --primary --mode 2560x1080 --pos 1366x0 --rotate normal --output VIRTUAL1 --off
	bspc monitor HDMI2 -d I II III IV V VI VII VIII
	bspc monitor eDP1 -d IX X
	bspc wm -O HDMI2 eDP1
	setxkbmap -layout us
else
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
	setxkbmap -model thinkpad -layout br -variant abnt2
fi

bspc config border_width 4
bspc config window_gap 16

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# App rules
bspc rule -a MEGAsync desktop='^10'

# start daemons
pgrep -x clipmenud >/dev/null || clipmenud &
pgrep -x megasync >/dev/null || megasync &
pgrep -x redshift >/dev/null || redshift &
pgrep -x unclutter >/dev/null || unclutter &

# restart daemons
pkill sxhkd
sxhkd &

pkill picom
sleep 0.1
picom --experimental-backends &

# launch polybar
[ -f $HOME/.config/polybar/launch.sh ] && $HOME/.config/polybar/launch.sh

feh --randomize --bg-fill ~/.wallpapers/
