#!/usr/bin/env sh

# Set screens
xrandr --output eDP1 --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --primary --mode 2560x1080 --pos 1366x0 --rotate normal --output VIRTUAL1 --off

# WM config
bspc monitor eDP1 -d IX X
bspc monitor HDMI2 -d I II III IV V VI VII VIII
bspc config border_width 4
bspc config window_gap 24

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# App rules
bspc rule -a MEGAsync desktop='^10'
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# start daemons
pgrep -x clipmenud >/dev/null || clipmenud &
pgrep -x megasync >/dev/null || megasync &
pgrep -x redshift >/dev/null || redshift &
pgrep -x unclutter >/dev/null || unclutter &

# restart daemons
pkill sxhkd
sxhkd &

pkill picom
sleep 0.1
picom --experimental-backends &

pkill polybar
polybar &

feh --randomize --bg-fill ~/.wallpapers/
