#!/usr/bin/env sh

# WM config
if xrandr --query | grep 'HDMI2 connected'; then
	xrandr --output eDP1 --mode 1366x768 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --primary --mode 2560x1080 --pos 1366x0 --rotate normal --output VIRTUAL1 --off
	bspc monitor HDMI2 -d I II III IV V VI VII VIII
	bspc monitor eDP1 -d IX X
	bspc wm -O HDMI2 eDP1
	setxkbmap -layout us
else
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
	setxkbmap -model thinkpad -layout br -variant abnt2
fi

bspc config border_width 4
bspc config window_gap 16

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#81a1c1"
bspc config presel_feedback_color "#81a1c1"

bspc desktop -f I

# App rules
bspc rule -a MEGAsync desktop='^10'

# start daemons
pgrep -f clipmenud >/dev/null || { clipmenud & }
pgrep -x picom >/dev/null || { picom --experimental-backends & }
pgrep -x redshift >/dev/null || { redshift & }
pgrep -x sxhkd >/dev/null || { sxhkd & }
pgrep -x unclutter >/dev/null || { unclutter & }

# pgrep -x megasync >/dev/null || { megasync & }

# launch polybar
[ -f $HOME/.config/polybar/launch.sh ] && $HOME/.config/polybar/launch.sh

feh --randomize --bg-fill ~/.wallpapers/

# this ensures bspwm terminates correctly (not working)

# if no processes where started by this script, we are done
[ -z "$(jobs -p)" ] && exit 0

# wait for bspwm to terminate
bspc subscribe >/dev/null

# kill all the processes started by this script
kill $(jobs -p)
