require("plugins.lazy")

require("core.settings")
require("core.keymaps")
require("core.lsp")
require("core.autocmds")

require("plugins.alpha")
require("plugins.bufferline")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.indent-blankline")
require("plugins.lualine")
require("plugins.marks")
require("plugins.neoscroll")
require("plugins.noice")
require("plugins.null-ls")
require("plugins.nvim-autopairs")
require("plugins.nvim-cmp")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.treesitter")
